from .import views
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

app_name = "api"

urlpatterns = [
    path('provinces', views.liste_provinces,name="provinces"),
    path('details-province', views.details_province,name="details_province"),
    path('villes', views.liste_villes,name="villes"),
    path('details-ville', views.details_ville,name="details_ville"),
    path('users', views.liste_users,name="users"),
    path('users/<int:pk>', views.details_user,name="details_user"),
    path('agents', views.liste_agents,name="agents"),
    path('agents/<int:pk>', views.details_agent,name="details_agents"),
    path('clients', views.liste_clients,name="clients"),
    path('details-client', views.details_client,name="details_client"),
    path('details-compteur', views.details_compteur,name="details_compteur"),
    path('abonnements', views.liste_abonnements,name="abonnements"),
    path('abonnements/<int:pk>', views.details_abonnement,name="details_abonnement"),
    path('machines', views.liste_machines,name="liste_machines"),
    path('uplink', views.publication_donnees,name="publications"),
    path('gateways', views.liste_gws,name="liste_gws"),
    path('liste-compteurs/<int:pk>', views.liste_compteur_client,name="liste_compteur_client"),
    path('donnees-historique', views.historique_donnees,name="historique_donnees"),
    #path('test', views.test_api,name="test_api"),
    path('activation', views.activation_compteur,name="activation_compteur"),
    path('auth-compteur', views.auth_compteur,name="auth_compteur"),
    path('recuperation-compteurs', views.recuperer_compteurs,name="recuperer_compteurs"),
    path('donnees-instantanees', views.afficher_donnees_instantanees,name="afficher_donnees_instantanees"),
    path('recharge-de-credit', views.recharge_credit,name="recharge_credit"),
    path('transfert-de-credit', views.transfert_credit,name="transfert_credit"),
    path('liste-des-transferts', views.afficher_transferts_effectues,name="afficher_transferts_effectues"),
    path('liste-des-transferts-entrants', views.afficher_transferts_entrants,name="afficher_transferts_entrants"),
    path('dernier-transfert', views.afficher_dernier_transfert,name="afficher_dernier_transfert"),
    path('derniere-recharge', views.afficher_derniere_recharge,name="afficher_derniere_recharge"),
    path('associer-compteur', views.associer_compteur,name="associer_compteur"),
    path('compteurs-associes', views.liste_compteurs_lies,name="liste_compteurs_lies"),
    path('supprimer-compteur-associe', views.supprimer_compteur_associe,name="supprimer_compteur_associe"),
    path('equivalence-unite-prix', views.equivalence_unite_prix,name="equivalence_unite_prix"),
    path('authentification-compteur-client', views.authentifier_compteur_client,name="authentifier_compteur_client"),
    path('compteurs-utilisateur', views.nombre_compteurs_utilisateur,name="nombre_compteurs_utilisateur"),
    path('rapport-transfert', views.rapport_dernier_transfert,name="rapport_dernier_transfert"),
    path('supprimer-favoris', views.supprimer_favoris,name="supprimer_favoris"),
    path('activer-votre-compteur', views.activer_compteur,name="activer_compteur"),
    path('ajouter-un-favoris', views.ajout_favoris,name="ajout_favoris"),
    path('retraits-effectues', views.afficher_retraits_effectues,name="afficher_retraits_effectues"),
    path('retirer-argent', views.retrait_argent,name="retrait_argent"),
    path('recharges-effectuees', views.recharges_effectuees,name="recharges_effectuees"),
    path('recharges-non-effectuees', views.recharges_non_effectuees,name="recharges_non_effectuees"),
    path('suppr', views.deleteC,name="deleteC"),
    path('retrancher-unites', views.retransher_unites,name="retransher_unites"),
    path('recuperer-client-via-code', views.recuperer_client,name="recuperer_client"),
    path('emprunter-unites', views.emprunter_unites,name="emprunter_unites"),
    path('supprimer-emprunts', views.deleteEmprunts,name="deleteEmprunts"),
    path('envoi', views.envoi_unites,name="envoi_unites"),
    path('reception', views.reception,name="reception_unites"),
    path('details-transfert', views.details_transac,name="details_transac"),
    path('envoi-message', views.envoi_sms,name="envoi_sms"),
    path('compteurs-personnel', views.liste_compteurs,name="liste_compteurs"),
    path('verification-du-client', views.verification_du_client,name="verification_du_client"),
    path('authentifier-code-client', views.authentifier_code,name="authentifier_code"),
    path('modifier-mot-de-passe-client', views.modifier_mot_de_passe,name="modifier_mot_de_passe"),
    path('changer-mot-de-passe-client', views.changer_mot_de_passe,name="changer_mot_de_passe"),
    path('recuperer-mot-de-passe-client', views.recuperer_mot_de_passe_client,name="recuperer_mot_de_passe_client"),
    path('details-achat', views.details_achat,name="details_achat"),
    path('details-retrait', views.details_retrait,name="details_retrait"),
    path('details-emprunt', views.details_emprunt,name="details_emprunt"),
    path('historique-retraits', views.historique_retraits,name="historique_retraits"),
    path('historique-emprunts', views.emprunts,name="emprunts"),
    path('supprimer-dette', views.supprimer_dette,name="supprimer_dette"),
]
urlpatterns = format_suffix_patterns(urlpatterns)

