# Generated by Django 4.0.5 on 2022-09-29 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elec_meter', '0005_etatcompteur_date_enregistre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(max_length=100)),
                ('date_notif', models.DateTimeField(default=django.utils.timezone.now)),
                ('motif', models.CharField(max_length=100)),
                ('compteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elec_meter.machine')),
            ],
        ),
    ]
