# Generated by Django 4.0.5 on 2022-08-05 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import elec_meter.models


class Migration(migrations.Migration):

    dependencies = [
        ('elec_meter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', elec_meter.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2022, 8, 5, 14, 25, 40, 701134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 14, 25, 40, 700135, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infosignal',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 14, 25, 40, 701134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='heure_retrait',
            field=models.TimeField(default='16:25:40'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='jour_retrait',
            field=models.DateField(default=datetime.datetime(2022, 8, 5, 16, 25, 40, 701135)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adresse email'),
        ),
    ]
