# Generated by Django 4.0.5 on 2022-08-08 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elec_meter', '0002_alter_user_managers_alter_abonnement_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2022, 8, 8, 11, 20, 19, 392501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 11, 20, 19, 375544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infosignal',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 11, 20, 19, 375544, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='heure_retrait',
            field=models.TimeField(default='13:20:19'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='jour_retrait',
            field=models.DateField(default=datetime.datetime(2022, 8, 8, 13, 20, 19, 392501)),
        ),
    ]
