# Generated by Django 4.0.5 on 2022-10-28 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elec_meter', '0005_etatcompteur_date_enregistre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargeettransfert',
            name='benef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiare_transac', to='elec_meter.machine'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2022, 10, 28, 10, 41, 2, 801220, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 10, 41, 2, 795184, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infosignal',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 10, 41, 2, 798217, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='heure_retrait',
            field=models.TimeField(default='12:41:02'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='jour_retrait',
            field=models.DateField(default=datetime.datetime(2022, 10, 28, 12, 41, 2, 805219)),
        ),
    ]
