# Generated by Django 4.0.5 on 2022-11-01 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elec_meter', '0006_rechargeettransfert_benef_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='montant_en_cfa',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 20, 26, 18, 713559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 20, 26, 18, 712524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infosignal',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 1, 20, 26, 18, 713559, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='heure_retrait',
            field=models.TimeField(default='21:26:18'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='jour_retrait',
            field=models.DateField(default=datetime.datetime(2022, 11, 1, 21, 26, 18, 713560)),
        ),
    ]
