# Generated by Django 4.0.5 on 2022-12-02 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('elec_meter', '0007_emprunt_montant_en_cfa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 13, 33, 35, 692399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 33, 35, 685743, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='infosignal',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 2, 13, 33, 35, 688601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='heure_retrait',
            field=models.TimeField(default='14:33:35'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='jour_retrait',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 14, 33, 35, 696479)),
        ),
    ]
